### ISSUE TITLE
NameError: name 'Registro001' is not defined no init do Bloco1 em pis_cofins

### ISSUE THREAD

**Issue by ragouveia** [sped-br/python-sped#11]
NameError: name 'Registro001' is not defined  é lançado no método **init** da classe Bloco1 do módulo efd.pis_cofins.

O registro de abertura deveria ser Registro0001 ao invés de Registro001

```
class Bloco1(Bloco):
    """
    Complemento da Escrituração – Controle de Saldos de Créditos e de  Retenções, Operações Extemporâneas e Outras Informações
    """
    def __init__(self):
        self._registro_abertura = Registro001()
        self._registro_fechamento = Registro0990()
```

**Comment by sergiogarciadev** [comment]
Isso havia sido corrigido mas acabou não indo pro PyPI. Foi gerado nova versão, por favor atualize com:

```
$ pip install --upgrade sped
```
