### ISSUE TITLE
Exemplo de utilização do pacote python-sped

### ISSUE THREAD

**Issue by eduardotd** [sped-br/python-sped#12]
Boa tarde,

Gostaria muito de tentar usar este pacote mas não estou conseguindo montar um programa básico para testar...

Alguém teria um exemplo simples criando registros e gerando o arquivo?

Muito obrigado desde já

**Comment by sergiogarciadev** [comment]
Tem um exemplo aqui #1.

**Comment by eduardotd** [comment]
Muito Obrigado!

2017-03-08 10:33 GMT-03:00 Sergio Garcia <notifications@github.com>:
