### ISSUE TITLE
Erro atualização : Pequenas correções no leiaute do ECF 2016. 

### ISSUE THREAD

**Issue by crsilveira** [sped-br/python-sped#20]
A atualização acima está gerando o seguinte erro : 
 ..sped-1.0.0-py3.6.egg/sped/efd/icms_ipi/arquivos.py", line 28, in __init__
    self._blocos['0'] = Bloco0()
TypeError: __init__() missing 1 required positional argument: 'nome'

Vi que foi adicionado : 

  class Bloco(object):
     def __init__(self):
     def __init__(self, nome):
         self._nome = nome

pode me ajudar como resolver ?

**Comment by sergiogarciadev** [comment]
Na master, eu fiz uma modificação para gerar as classes com base em um arquivo contendo os tipos daquela versão do leiaute, permitindo assim usar múltiplos leiautes na mesma versão da biblioteca. Porém implementei isso somente para ECD e ECF.

Eu tornei o parâmetro nome opcional assim não quebra o EFD.
