### ISSUE TITLE
Atribuição do campo "TP_CT-e" no registro D100

### ISSUE THREAD

**Issue by leogregianin** [sped-br/python-sped#27]
Como atribuir o campo "TP_CT-e" no registro D100?

https://github.com/sped-br/python-sped/blob/f01c3ace33ff3030415c4f53cc82ba2da57a18f9/sped/efd/icms_ipi/registros.py#L1389

Exemplo de uso:

```python
        bloco_d = arquivo._blocos['D']
        reg_d100 = RegistroD100()
        (...)
        reg_d100.TP_CT-e = ''
```

Erro: can't assign to binary operator

**Comment by sergiogarciadev** [comment]
Você pode acessar os registros como um dicionário:

```py
reg_d100['TP_CT-e'] = ''
```
